name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the devbox image
        run: docker build . --file Dockerfile --tag devbox:ci

      - name: Build project inside devbox
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            devbox:ci \
            bash -c 'source "/opt/esp/esp-idf/export.sh" && make build'
